### ISSUE TITLE
Battle.comparePriority() is not deterministic

### ISSUE THREAD

**Issue by Alphadelta14** [Zarel/Pokemon-Showdown#2120] opened 2015-08-19 04:06 UTC
When resolving events for the engine's `Battle.queue`, `Math.random()` is used to break all ties including actual internal mechanics ties such as move order resolution. If the same state is applied multiple times, the results may vary under the rare case that there is a perfect tie.

**Comment by Slayer95** [comment] 2015-08-19 04:39
Duplicate of https://github.com/Zarel/Pokemon-Showdown/issues/1157

**Closed by Slayer95** 2015-08-19 04:39 UTC
