### ISSUE TITLE
Feature Request: Import team directly from PokePaste URL

### ISSUE THREAD

**Issue by HarounAns** [Zarel/Pokemon-Showdown#5758] opened 2019-09-04 20:13 UTC
I have a feature request, where instead of the user having to copy and paste the entire team into the importable section of the team builder, the user instead just pastes the link of the pokepaste into it, and it auto generates the team. 

So instead of having to do this:
![image](https://user-images.githubusercontent.com/20847319/64287600-1e946e00-cf2e-11e9-872e-85fc4337a420.png)

You can do this instead:
![image](https://user-images.githubusercontent.com/20847319/64287652-408df080-cf2e-11e9-9529-93ef29eb291f.png)

And then it autogenerates the team
![image](https://user-images.githubusercontent.com/20847319/64287700-64513680-cf2e-11e9-8587-14f55fc9c796.png)

**Comment by Zarel** [comment] 2019-09-04 20:22
I think @scheibo was working on this?

**Comment by scheibo** [comment] 2019-09-04 20:37
This is a dupe of https://github.com/Zarel/Pokemon-Showdown-Client/issues/1349

**Closed by scheibo** 2019-09-04 20:37 UTC
