### ISSUE TITLE
[Suggest] How about doing translation project?

### ISSUE THREAD

**Issue by AhnMinGyu** [Zarel/Pokemon-Showdown#2432] opened 2016-02-27 09:56 UTC
How about starting a project about translation? Like Japanese, German, French, Korean , Italian.... 
Accept user-made translation in GitHub.

**Comment by Zarel** [comment] 2016-02-27 10:05
Duplicate of Zarel/Pokemon-Showdown-Client#247

**Closed by Zarel** 2016-02-27 10:05 UTC
